import "@mantine/core/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { theme } from "@/lib/theme";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto"/>
      </head>
      <body>
        <main>
          <MantineProvider defaultColorScheme="auto" theme={theme}>{children}</MantineProvider>
        </main>
      </body>
    </html>
  );
}
